name: .NET Core

on:
  push:
    branches: [ unstable ]
  pull_request:
    branches: [ unstable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.400
    - name: Install dependencies
      run: pwd && dotnet restore src/MarkDoc.sln
    - name: Build
      run: pwd && dotnet build src/MarkDoc.sln --configuration Release --no-restore
